name: CI Backend

on:
  push:
    branches: [ "main", "master" ]

  pull_request:
    branches: [ "main", "master" ]

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código del repositorio
        uses: actions/checkout@v4

      - name: Instalar Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Instalar dependencias del backend
        run: |
          cd backend
          npm ci

      - name: Ejecutar pruebas del backend
        run: |
          cd backend
          npm test